var Nightmare = require("nightmare");
var lib = require("wat_scenario");
var scenario = new lib.Scenario();
scenario.addAction(new lib.GotoAction("http://localhost:8888/dolibarr-7.0.0/htdocs/index.php"));
scenario.addAction(new lib.TypeAction("#username", "admin"));
scenario.addAction(new lib.TypeAction("#password", "123456"));
scenario.addAction(new lib.ClickAction("#login_line2 > INPUT:nth-child(2)"));
scenario.addAction(new lib.ClickAction('#id-left > DIV:nth-child(1) > DIV:nth-child(5) > DIV:nth-child(1) > A:nth-child(1)'));
scenario.addAction(new lib.ClickAction('#id-left > DIV:nth-child(1) > DIV:nth-child(5) > DIV:nth-child(4) > A:nth-child(1)'));
scenario.addAction(new lib.ClickAction('#searchFormList > DIV:nth-child(6) > DIV:nth-child(8) > TABLE:nth-child(1) > TBODY:nth-child(1) > TR:nth-child(1) > TD:nth-child(6) > A:nth-child(1) > IMG:nth-child(1)'));
scenario.addAction(new lib.ClickAction("#usergroupcard"));
scenario.addAction(new lib.TypeAction("[cols]", "DOL_DATA_ROOT/doctemplates/usergroups"));
scenario.addAction(new lib.ClickAction('[value="Modify"]'));
process.send(scenario);
