var Nightmare = require("nightmare");
var lib = require("wat_scenario");
var scenario = new lib.Scenario();
scenario.addAction(new lib.GotoAction("http://localhost:8888/dolibarr-7.0.0/htdocs/index.php"));
scenario.addAction(new lib.TypeAction("#username", "admin"));
scenario.addAction(new lib.TypeAction("#password", "123456"));
scenario.addAction(new lib.ClickAction("#login_line2 > INPUT:nth-child(2)"));
scenario.addAction(new lib.ClickAction("#id-left > DIV:nth-child(1) > DIV:nth-child(5) > DIV:nth-child(1) > A:nth-child(1)"));
scenario.addAction(new lib.ClickAction("#id-left > DIV:nth-child(1) > DIV:nth-child(5) > DIV:nth-child(4) > A:nth-child(1)"));
scenario.addAction(new lib.ClickAction("#searchFormList > DIV:nth-child(6) > DIV:nth-child(8) > TABLE:nth-child(1) > TBODY:nth-child(1) > TR:nth-child(1) > TD:nth-child(6) > A:nth-child(1) > IMG:nth-child(1)"));
scenario.addAction(new lib.ClickAction("#attributes"));
scenario.addAction(new lib.ClickAction(".butAction"));
scenario.addAction(new lib.TypeAction("tr:nth-of-type(1) [type]", "testLabel"));
scenario.addAction(new lib.TypeAction("#attrname", "c123456"));
scenario.addAction(new lib.SelectAction('[name="type"]', 'varchar'));
scenario.addAction(new lib.ClickAction('[action] [align] .button:nth-of-type(1)'));
process.send(scenario);
