var Nightmare = require("nightmare");
var lib = require("wat_scenario");
var scenario = new lib.Scenario();
scenario.addAction(new lib.GotoAction("http://localhost:8888/dolibarr-7.0.0/htdocs/index.php"));
scenario.addAction(new lib.TypeAction("#username", "admin"));
scenario.addAction(new lib.TypeAction("#password", "123456"));
scenario.addAction(new lib.ClickAction("#login_line2 > INPUT:nth-child(2)"));
scenario.addAction(new lib.ClickAction("#id-left > DIV:nth-child(1) > DIV:nth-child(7) > DIV:nth-child(1) > A:nth-child(1)"));
scenario.addAction(new lib.ClickAction('#id-left > DIV:nth-child(1) > DIV:nth-child(7) > DIV:nth-child(9) > A:nth-child(1)'));
scenario.addAction(new lib.ClickAction('[href="card\.php\?id\=1"]'));
scenario.addAction(new lib.ClickAction('#id-right > DIV:nth-child(1) > DIV:nth-child(3) > A:nth-child(1)'));
scenario.addAction(new lib.TypeAction("#id-right > DIV:nth-child(1) > FORM:nth-child(1) > DIV:nth-child(4) > TABLE:nth-child(1) > TBODY:nth-child(1) > TR:nth-child(1) > TD:nth-child(2) > INPUT:nth-child(1)", "testNewGroup"));
scenario.addAction(new lib.TypeAction("#note", "try to test a new group. description"));
scenario.addAction(new lib.ClickAction('[value="Save"]'));
process.send(scenario);
