var Nightmare = require("nightmare");
var lib = require("wat_scenario");
var scenario = new lib.Scenario();
scenario.addAction(new lib.GotoAction("http://localhost:8888/Joomla_3_7_0/"));
scenario.addAction(new lib.TypeAction("#modlgn-username", "admin"));
scenario.addAction(new lib.TypeAction("#modlgn-passwd", "123456"));
scenario.addAction(new lib.ClickAction("#form-login-submit > DIV:nth-child(1) > BUTTON:nth-child(1)"));
scenario.addAction(new lib.ClickAction("HTML > BODY:nth-child(2) > DIV:nth-child(1) > DIV:nth-child(1) > DIV:nth-child(3) > DIV:nth-child(2) > DIV:nth-child(3) > UL:nth-child(2) > LI:nth-child(4) > A:nth-child(1)"));
scenario.addAction(new lib.TypeAction("#params_sitetitle", "templateTitle"));
scenario.addAction(new lib.ClickAction("#templates-form > DIV:nth-child(1) > DIV:nth-child(1) > DIV:nth-child(1) > BUTTON:nth-child(1)"));
process.send(scenario);
